name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
      
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: install graphviz
      run: sudo apt-get install graphviz

    - uses: actions/checkout@v2

    - uses: "ramsey/composer-install@v1"
      with:
        composer-options: "--ansi --prefer-dist"

    - name: Download REDAXO
      run: curl -sLo redaxo_main.zip https://github.com/redaxo/redaxo/archive/main.zip

    - name: Extract REDAXO
      run: unzip redaxo_main.zip -d .

    - name: phpdoc cache
      uses: actions/cache@v1
      with:
        path: .phpdoc
        key: branch-${{ github.ref }}

    - name: Cleanup dev files
      run: rm -rf redaxo-main/.{github,idea,tools}

    - name: Generate phpdoc - clean template
      run: vendor/bin/phpdoc project:run --target output --directory redaxo-main --ignore "**/tests" --ignore "**/vendor" --force --visibility=public,protected --sourcecode --template=clean

    - name: Generate phpdoc - default template
      run: vendor/bin/phpdoc project:run --target output/default --directory redaxo-main --ignore "**/tests" --ignore "**/vendor" --force --visibility=public,protected --sourcecode --template=default

    - name: Deploy to Github Pages
      uses: peaceiris/actions-gh-pages@v1.1.0
      if: success() && github.ref == 'refs/heads/master'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./output

    - name: Trigger page build
      if: success() && github.ref == 'refs/heads/master'
      run: "curl 'https://api.github.com/repos/FriendsOfREDAXO/phpdoc/pages/builds' -X POST -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' -H 'Accept: application/vnd.github.mister-fantastic-preview'"
