name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: install graphviz
      run: sudo apt-get install graphviz
    - uses: actions/checkout@v1
    - name: run composer
      run: composer install
    - name: Download REDAXO
      run: curl -sLo redaxo_master.zip https://github.com/redaxo/redaxo/archive/master.zip
    - name: Extract REDAXO
      run: unzip redaxo_master.zip -d redaxo_master
    - name: Generate phpdoc
      run: vendor/bin/phpdoc project:run --target output --directory redaxo_master --ignore '*/tests/*,*/vendor/*' --force --visibility=public,protected --sourcecode --parseprivate --template=clean
    - name: Deploy to Github Pages
      uses: peaceiris/actions-gh-pages@v1.1.0
      if: success() && github.ref == 'master'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./output
    - name: Trigger page build
      if: success() && github.ref == 'master'
      run: "curl 'https://api.github.com/repos/FriendsOfREDAXO/phpdoc/pages/builds' -X POST -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' -H 'Accept: application/vnd.github.mister-fantastic-preview'"

